### PR TITLE
not fallback to get request on 405 only

### PR DESCRIPTION
**Pull request by john0isaac**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        |  yes                             |
| Related issues? | https://github.com/Azure-Samples/azure-search-openai-demo/pull/2124 |

## What's in this Pull Request?

We will attempt to send a head request then get request on all urls until a request returns 200 or the retries are 0

### CODE REVIEW

**Comment by john0isaac** [comment]
@pamelafox tech community was returning 400 not 405 when you send a head request that's why the get request was never executed.
I fixed this but it will make the workflow take more time to execute as it will try head and get 3 times for 10 seconds on each url before flagging it as broken (only if the url is not working) if your urls are working it shouldn't change the execution time of the workflow.

**Comment by john0isaac** [comment]
Right now I'm thinking of adding a `fail-fast` cli flag as it could take forever to finish if you have many broken urls 😆

**Comment by pamelafox** [comment]
Agreed that this can affect potential execution time. I'll keep an eye out for that. Thanks for making the fix! I assume we need to upgrade the version in the workflow for azure-search-openai-demo?

**Comment by john0isaac** [comment]
Nope, the workflow always uses the latest version of the python package.
No more changes are required it will work right away.

**Comment by pamelafox** [comment]
Ah, great, thanks so much!

**Pull request merged**
